import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { TwicInstall } from "@twicpics/components/react";
import "@twicpics/components/style.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
        {/* <div data-theme="dark" className="h-full bg-zinc-950"> */}
        <div data-theme="dark" className="h-screen">
        <TwicInstall
        // domain is mandatory //prev written h-screen bs
        domain="https://sebonti.twic.pics"
        />
        {children}
        <ToastContainer />
        </div>
        </body>
    </html>
    </ClerkProvider>
  );
}
